/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as PricingAssistantRouteImport } from './routes/pricing-assistant'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BusinessProfileRouteImport } from './routes/business-profile'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'

const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingAssistantRoute = PricingAssistantRouteImport.update({
  id: '/pricing-assistant',
  path: '/pricing-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/business-profile',
  path: '/business-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-profile': typeof BusinessProfileRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/pricing-assistant': typeof PricingAssistantRoute
  '/rates': typeof RatesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-profile': typeof BusinessProfileRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/pricing-assistant': typeof PricingAssistantRoute
  '/rates': typeof RatesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-profile': typeof BusinessProfileRoute
  '/clients': typeof ClientsRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/pricing-assistant': typeof PricingAssistantRoute
  '/rates': typeof RatesRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-profile'
    | '/clients'
    | '/contact'
    | '/documents'
    | '/pricing-assistant'
    | '/rates'
    | '/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-profile'
    | '/clients'
    | '/contact'
    | '/documents'
    | '/pricing-assistant'
    | '/rates'
    | '/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/business-profile'
    | '/clients'
    | '/contact'
    | '/documents'
    | '/pricing-assistant'
    | '/rates'
    | '/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  ClientsRoute: typeof ClientsRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  PricingAssistantRoute: typeof PricingAssistantRoute
  RatesRoute: typeof RatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing-assistant': {
      id: '/pricing-assistant'
      path: '/pricing-assistant'
      fullPath: '/pricing-assistant'
      preLoaderRoute: typeof PricingAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-profile': {
      id: '/business-profile'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  ClientsRoute: ClientsRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  PricingAssistantRoute: PricingAssistantRoute,
  RatesRoute: RatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
